name = "ai-agents-webapp-worker"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
compatibility_date = "2023-12-01"

[build]
command = "npm run build:worker"
watch_dir = "src"

[build.upload]
format = "service-worker"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

[env.development]
vars = { ENVIRONMENT = "development" }

[[kv_namespaces]]
binding = "PLANS_STORAGE"
id = ""
preview_id = ""

[[kv_namespaces]]
binding = "AGENT_STORAGE"
id = ""
preview_id = ""

[[d1_databases]]
binding = "DB"
database_name = "ai_agents_db"
database_id = ""
preview_database_id = ""

[durable_objects]
bindings = [
  { name = "AGENT_SESSIONS", class_name = "AgentSession" }
]

[[migrations]]
tag = "v1"
new_classes = ["AgentSession"]

[site]
bucket = "../frontend/build"
entry-point = "."

[triggers]
crons = ["*/5 * * * *"]
