name = "airountable-api"
main = "src/index.js"
compatibility_date = "2023-12-01"

[vars]
ENVIRONMENT = "production"
API_PATH = "api"
FRONTEND_DOMAIN = "airountable.com"

[[d1_databases]]
binding = "DB"
database_name = "ai_agents_db"
database_id = "6a8a09a7-3413-4b94-9e5c-b763cea716ad"

[[kv_namespaces]]
binding = "PLANS_STORAGE"
id = "null"

[[kv_namespaces]]
binding = "AGENT_STORAGE"
id = "null"

[triggers]
crons = ["*/5 * * * *"]
